// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcDVqnXPxCo3QfRjebO1Ze9HEOHYZCZE',
    appId: '1:580096241925:web:5bd9886125dab3a308c76c',
    messagingSenderId: '580096241925',
    projectId: 'prueba-c964b',
    authDomain: 'prueba-c964b.firebaseapp.com',
    databaseURL: 'https://prueba-c964b-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-c964b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAVdCGNjxYV0aIry7IPY0BYN2FHktTgw',
    appId: '1:580096241925:android:0d87bd7d38bead5b08c76c',
    messagingSenderId: '580096241925',
    projectId: 'prueba-c964b',
    databaseURL: 'https://prueba-c964b-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-c964b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkquPPsvHXLxmi6gcwhC8eSOXwE_65iWI',
    appId: '1:580096241925:ios:3e0ca203b2cc8bf608c76c',
    messagingSenderId: '580096241925',
    projectId: 'prueba-c964b',
    databaseURL: 'https://prueba-c964b-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-c964b.appspot.com',
    iosBundleId: 'com.example.plaza_libre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkquPPsvHXLxmi6gcwhC8eSOXwE_65iWI',
    appId: '1:580096241925:ios:3e0ca203b2cc8bf608c76c',
    messagingSenderId: '580096241925',
    projectId: 'prueba-c964b',
    databaseURL: 'https://prueba-c964b-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-c964b.appspot.com',
    iosBundleId: 'com.example.plaza_libre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApcDVqnXPxCo3QfRjebO1Ze9HEOHYZCZE',
    appId: '1:580096241925:web:084623094d42d21508c76c',
    messagingSenderId: '580096241925',
    projectId: 'prueba-c964b',
    authDomain: 'prueba-c964b.firebaseapp.com',
    databaseURL: 'https://prueba-c964b-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-c964b.appspot.com',
  );

}